<a href="https://colab.research.google.com/github/fmr693/Evaluaci-n-DEVOPS/blob/main/ejercicios_numpy_cap4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ejercicios – NumPy Básico
**Python for Data Analysis** – Cap. 4

Completa cada celda de código con tu solución.

In [ ]:
import numpy as np

---
## Parte 1 – Creación de arrays

### Ejercicio 1.
Crea los siguientes arrays y muestra su `shape` y `dtype` para cada uno:
- Un array 1-D con los números del 0 al 9 usando `np.arange`.
- Un array 2-D de forma (3, 4) lleno de ceros.
- Un array de forma (2, 2) lleno de unos, con tipo de dato `int32`.

In [ ]:
array1 =np.arange(0,10)
print(array1)
print(array1.dtype)
print(array1.shape)

Lista = [[0,0,0],[0,0,0]]
array2 = np.array(Lista)
print(Array2)
print(array2.dtype)
print(array2.shape)

[0 1 2 3 4 5 6 7 8 9]
int64
(10,)
[[0 0 0]
 [0 0 0]]
int64
(2, 3)


### Ejercicio 2.
Dado el siguiente objeto Python, conviértelo en un ndarray de NumPy e inspecciona su `ndim`, `shape` y `dtype`:
```python
datos = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]
```

In [ ]:
# Tu código aquí


### Ejercicio 3.
Crea una matriz identidad de 4×4 usando la función adecuada de NumPy. ¿Qué función del libro se usa para esto?

In [ ]:
matrix = np.eye(4) #funcion .eye
print(matrix)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


---
## Parte 2 – Tipos de datos y conversión

### Ejercicio 4.
Crea el array `arr = np.array([1.8, -2.5, 3.3, 0.7])` y conviértelo a entero (`int32`) usando `astype`. ¿Qué le ocurre a la parte decimal?

In [ ]:
# Tu código aquí


### Ejercicio 5.
Tienes el siguiente array de cadenas que representan números:
```python
numeros = np.array(["3.14", "2.71", "1.41"], dtype=np.string_)
```
Conviértelo a tipo `float64` usando `astype` y verifica el resultado.

In [ ]:
# Tu código aquí


---
## Parte 3 – Operaciones aritméticas vectorizadas

### Ejercicio 6.
Crea el array `a = np.array([[1, 2, 3], [4, 5, 6]])` y realiza las siguientes operaciones sin usar bucles:
- Multiplica todos sus elementos por 3.
- Suma el array consigo mismo.
- Eleva cada elemento al cuadrado (`a ** 2`).

In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)

matrix2 = 3 * matrix
print(matrix2)

matrix3 = matrix + matrix
print(matrix3)

matrix4 = matrix ** 2
print(matrix4)


[[1 2 3]
 [4 5 6]]
[[ 3  6  9]
 [12 15 18]]
[[ 2  4  6]
 [ 8 10 12]]
[[ 1  4  9]
 [16 25 36]]


### Ejercicio 7.
Dados dos arrays:
```python
x = np.array([10.0, 20.0, 30.0])
y = np.array([1.0, 2.0, 3.0])
```
Calcula `x / y`, `x - y`, `x**2`.
¿Qué tipo de operaciones son estas, componente a componente o expansión de escalares?

In [ ]:
x = np.array([10.0, 20.0, 30.0])
y = np.array([1.0, 2.0, 3.0])

matrix = x / y
print(matrix)

matrix2 = x - y
print(matrix2)

matrix3 = x ** 2
print(matrix3)




[10. 10. 10.]
[ 9. 18. 27.]
[100. 400. 900.]


---
## Parte 4 – Indexación y slicing

### Ejercicio 8.
Crea el array `arr = np.arange(10)`.
- Selecciona el elemento en la posición 5.
- Selecciona los elementos del índice 2 al 6 (sin incluirlo).
- Cambia los elementos del índice 0 al 3 (sin incluirlo) por el valor 99 y observa qué ocurre con el array original.

In [ ]:
matrix = np.arange(10)
print(matrix)

arr_slice = matrix [5:6]
print(arr_slice)

arr_slice = matrix[2:6]
print(arr_slice)

arr_slice = matrix [0:3] = 99
print(arr_slice)



[0 1 2 3 4 5 6 7 8 9]
[5]
[2 3 4 5]
99


### Ejercicio 9.
Crea el siguiente array 2-D:
```python
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
```
- Selecciona el elemento de la fila 1, columna 2.
- Selecciona toda la segunda columna.
- Selecciona las dos primeras filas y las dos primeras columnas (submatriz 2×2).

In [ ]:
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

mat[0, 1]
mat[:, 1]
mat[0:2, 0:2]





array([[1, 2],
       [4, 5]])

---
## Parte 5 – Funciones universales (ufuncs)

### Ejercicio 10.
Usa las funciones universales del capítulo para:
- Calcular la raíz cuadrada de `np.array([4, 9, 16, 25, 36])`.
- Calcular el valor absoluto de `np.array([-3, -1, 0, 2, -5])`.
- Dados `a = np.array([1, 5, 3])` y `b = np.array([4, 2, 6])`, obtén el máximo elemento a elemento con `np.maximum`.

In [ ]:
# Tu código aquí


---
## Parte 6 – Generación de números aleatorios

### Ejercicio 11.
Usando `np.random`:
- Genera una matriz de forma (3, 3) con valores aleatorios de una distribución normal estándar.
- Fija una semilla (`seed`) con el valor 42 y genera 5 números aleatorios uniformes entre 0 y 1. Vuelve a ejecutar con la misma semilla y verifica que los resultados son idénticos.

In [ ]:

matriz_normal = np.random.randn(3, 3)
print(matriz_normal)


np.random.seed(42)

uniformes = np.random.rand(5)
print(uniformes)

np.random.seed(42)
uniformes2 = np.random.rand(5)
print(uniformes2)



[[-0.46947439  0.54256004 -0.46341769]
 [-0.46572975  0.24196227 -1.91328024]
 [-1.72491783 -0.56228753 -1.01283112]]
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


---
## Parte 7 – Álgebra lineal

### Ejercicio 12.
Dadas las matrices:
```python
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
```
- Calcula el producto matricial usando `np.dot` o el operador `@`.
- Calcula la transpuesta de `A`.

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

result = A @ B
print(result)

transpuesta = A.T
print(transpuesta)

[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


---
## Parte 8 – Selección booleana

### Ejercicio 13.
Dado el array:
```python
arr = np.array([15, -3, 8, -10, 22, 0, -7, 5])
```
- Crea una máscara booleana que identifique los valores mayores que 0.
- Usa esa máscara para seleccionar solo los valores positivos.
- Selecciona en un solo paso los valores menores que −5 o mayores que 10 usando operadores booleanos (`&` y `|`).

In [ ]:
arr = np.array([15, -3, 8, -10, 22, 0, -7, 5])

maskpositivos = arr > 0
print(maskpositivos)

positivos = arr[maskpositivos]
print(positivos)

filtrados = arr[(arr < -5) | (arr > 10)]
print(filtrados)


[ True False  True False  True False False  True]
[15  8 22  5]
[ 15 -10  22  -7]


### Ejercicio 14.
Crea la siguiente matriz:
```python
mat = np.array([[ 1, -2,  3],
                [-4,  5, -6],
                [ 7, -8,  9]])
```
- Selecciona todos los elementos negativos de la matriz usando indexación booleana.
- Reemplaza todos los elementos negativos por el valor 0 y muestra el resultado.
- Crea una copia de la matriz original y reemplaza todos los valores mayores que 5 por 99.

In [ ]:
mat = np.array([[ 1, -2,  3],
                [-4,  5, -6],
                [ 7, -8,  9]])

negativos = mat[mat < 0]
print(negativos)

mat[mat < 0] = 0
print(mat)

mat[mat > 5] = 99
print(mat)


[-2 -4 -6 -8]
[[1 0 3]
 [0 5 0]
 [7 0 9]]
[[ 1  0  3]
 [ 0  5  0]
 [99  0 99]]


### Ejercicio 15.
Dado el array de nombres y el array de datos asociados:
```python
nombres = np.array(["Ana", "Luis", "Ana", "Pedro", "Luis"])
datos   = np.array([10, 20, 30, 40, 50])
```
- Usa una condición booleana sobre `nombres` para seleccionar los datos correspondientes a `"Ana"`.
- Haz lo mismo para obtener los datos que **no** son de `"Luis"` usando el operador `~`.

In [ ]:
nombres = np.array(["Ana", "Luis", "Ana", "Pedro", "Luis"])
datos   = np.array([10, 20, 30, 40, 50])

datos_ana = datos[nombres == "Ana"]
print("Datos de Ana:", datos_ana)

datos_no_luis = datos[~(nombres == "Luis")]
print("Datos que no son de Luis:", datos_no_luis)




Datos de Ana: [10 30]
Datos que no son de Luis: [10 30 40]


---
## Parte 9 – Métodos estadísticos

### Ejercicio 16.
Crea el array `arr = np.array([4.0, 7.5, 2.1, 9.3, 5.8, 3.2, 8.0, 1.4])` y calcula:
- La suma total con `.sum()`.
- La media con `.mean()`.
- La desviación estándar con `.std()`.
- El valor mínimo y máximo con `.min()` y `.max()`.
- Los índices del mínimo y del máximo con `argmin()` y `argmax()`.

In [ ]:
arr = np.array([4.0, 7.5, 2.1, 9.3, 5.8, 3.2, 8.0, 1.4])

sumatorio = arr.sum()
print("suma total:", sumatorio)

media = arr.mean()
print("media:", media)

desviacion = arr.std()
print("desviacion:", desviacion)

minimo = arr.min()
maximo = arr.max()
print("el minimo y el maximo son:", minimo, "", maximo)

indmin = arr.argmin()
indmax = arr.argmax()
print("el indice del minimo es:", indmin, "y el maximo es:", indmax)





suma total: 41.3
media: 5.1625
desviacion: 2.733558806757228
el minimo y el maximo son: 1.4  9.3
el indice del minimo es: 7 y el maximo es: 3


### Ejercicio 17.
Crea la siguiente matriz 2-D:
```python
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]], dtype=float)
```
Calcula:
- La suma de todos los elementos (sin especificar eje).
- La suma por columnas (`axis=0`).
- La suma por filas (`axis=1`).
- La media por filas (`axis=1`).

In [37]:
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]], dtype=float)

sumanormal = mat.sum()
print(sumanormal)

suma_columnas = mat.sum(axis=0)
print("Suma por columnas:", suma_columnas)

suma_filas = mat.sum(axis=1)
print("Suma por filas:", suma_filas)

media_filas = mat.mean(axis=1)
print("Media por filas:", media_filas)

45.0
Suma por columnas: [12. 15. 18.]
Suma por filas: [ 6. 15. 24.]
Media por filas: [2. 5. 8.]


### Ejercicio 18.
Dado un array de 50 valores generados con `np.random.randn(50)`:
- Calcula cuántos valores son positivos usando `.sum()` sobre una expresión booleana.
- Calcula la proporción de valores positivos usando `.mean()` sobre la misma expresión.
- Ordena el array con `np.sort()` y verifica que el primer y último elemento son el mínimo y máximo.

In [33]:
arr = np.random.randn(50)
print(arr)

positivos = arr > 0
numpositivos = positivos.sum()
print(numpositivos)

prop_positivos = (arr > 0).mean()
print("Proporción de valores positivos:", prop_positivos)

arr_ordenado = np.sort(arr)


[ 1.55285978 -0.43951788 -0.40791535  0.26162306  0.01214651  0.93093408
 -0.52318809  0.94914299 -0.2392248   0.85397471 -0.27104046 -0.61309468
  1.91231764  1.06522708 -1.7920451  -0.44677351  1.20492292 -1.19666047
  0.77067833  0.6670561  -0.69914658 -0.00881705 -2.09001775  1.77043152
 -0.30909251  0.80381305  0.61384134  1.35788079 -0.43330341  0.20382273
  0.5591092   0.87254159  1.15435434 -0.47738173 -0.66422744  1.36011137
 -2.03707593  1.57003228 -0.30232424 -0.00456283 -0.6823426  -0.04819549
  1.27113823  0.7708631   0.49268648  0.08887301 -1.44560997 -0.84413691
 -0.34320124  0.45767645]
26
Proporción de valores positivos: 0.52


### Ejercicio 19.
Usa `np.unique()` para encontrar los valores únicos del siguiente array y comprueba cuántos hay:
```python
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])
```
Además, usa `np.sort()` sobre el array original para ver los elementos en orden ascendente.

In [41]:
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3, 5])

unicos = np.unique(arr)
print(unicos)

sorted = np.sort(unicos)
print(sorted)



[1 2 3 4 5 6 9]
[1 2 3 4 5 6 9]


---
## Parte 10 – Lógica condicional con np.where

### Ejercicio 20.
Dados los siguientes arrays:
```python
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
```
- Usa `np.where(cond, xarr, yarr)` para obtener un array que tome valores de `xarr` donde `cond` es `True` y de `yarr` donde es `False`. Verifica que el resultado es `[1.1, 2.2, 1.3, 1.4, 2.5]`.
- Crea una matriz aleatoria 4×4 con `rng.standard_normal((4, 4))` y usa `np.where` para reemplazar todos los valores positivos por 2 y los negativos por −2.

In [49]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])


resultado = np.where(cond, xarr, yarr)
print(resultado)

rng = np.random.default_rng(42)
matriz = rng.standard_normal((4, 4))
print("Matriz original:\n", matriz)

matriz_mod = np.where(matriz > 0, 2, -2)
print("Matriz modificada:\n", matriz_mod)



[1.1 2.2 1.3 1.4 2.5]
Matriz original:
 [[ 0.30471708 -1.03998411  0.7504512   0.94056472]
 [-1.95103519 -1.30217951  0.1278404  -0.31624259]
 [-0.01680116 -0.85304393  0.87939797  0.77779194]
 [ 0.0660307   1.12724121  0.46750934 -0.85929246]]
Matriz modificada:
 [[ 2 -2  2  2]
 [-2 -2  2 -2]
 [-2 -2  2  2]
 [ 2  2  2 -2]]


### Ejercicio 21.
`np.where` también acepta escalares en lugar de arrays. Dado el array:
```python
arr = np.array([-3.0, 1.5, -0.8, 4.2, -2.1, 0.0, 3.7])
```
- Usa `np.where` para reemplazar solo los valores positivos por 2, manteniendo los negativos y el cero sin cambio.
- Haz lo contrario: mantén los positivos y reemplaza los negativos y el cero por 0.
- Compara el resultado con el que obtendrías usando una list comprehension equivalente. ¿Cuál de los dos enfoques prefiere NumPy y por qué?

In [53]:
arr = np.array([-3.0, 1.5, -0.8, 4.2, -2.1, 0.0, 3.7])

arrmodificado1 = np.where(arr > 0, 2, arr)
print(arrmodificado1)

arrmodificado2 = np.where(arr <= 0, 0, arr)
print(arrmodificado2)


arr_listcomp = np.array([2 if x > 0 else x for x in arr])
print(arr_listcomp)


arr_listcomp2 = np.array([x if x > 0 else 0 for x in arr])
print(arr_listcomp2)

[-3.   2.  -0.8  2.  -2.1  0.   2. ]
[0.  1.5 0.  4.2 0.  0.  3.7]
[-3.   2.  -0.8  2.  -2.1  0.   2. ]
[0.  1.5 0.  4.2 0.  0.  3.7]


---
## Parte 11 – Métodos de conjuntos

### Ejercicio 23.
Dado el array con valores repetidos:
```python
nombres = np.array(["Bob", "Will", "Joe", "Bob", "Will", "Joe", "Joe"])
```
- Usa `np.unique()` para obtener los valores únicos ordenados. Compara el resultado con `sorted(set(nombres))`.
- Dado `values = np.array([6, 0, 0, 3, 2, 5, 6])`, usa `np.in1d(values, [2, 3, 6])` para obtener una máscara booleana. ¿Cuántos elementos cumplen la condición?

In [59]:
nombres = np.array(["Bob", "Will", "Joe", "Bob", "Will", "Joe", "Joe"])

nombresord = np.unique(nombres)
print(nombresord)


values = np.array([6, 0, 0, 3, 2, 5, 6])

mask = np.in1d(values, [2, 3, 6])
print(mask)

['Bob' 'Joe' 'Will']
[ True False False  True  True False  True]


/tmp/ipython-input-2353123531.py:9: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  mask = np.in1d(values, [2, 3, 6])


### Ejercicio 24.
Dados los siguientes dos arrays:
```python
a = np.array([1, 2, 3, 4, 5])
b = np.array([3, 4, 5, 6, 7])
```
- Usa `np.intersect1d(a, b)` para obtener los elementos comunes.
- Usa `np.union1d(a, b)` para obtener todos los elementos sin repetición.
- Usa `np.setdiff1d(a, b)` y después `np.setdiff1d(b, a)`. ¿Son iguales los resultados?

In [61]:
from sys import intern
a = np.array([1, 2, 3, 4, 5])
b = np.array([3, 4, 5, 6, 7])

interseccion = np.intersect1d(a, b)
print(interseccion)

union = np.union1d(a, b)
print(union)

diff1 = np.setdiff1d(a, b)
print(diff1)

diff2 = np.setdiff1d(b, a)
print(diff2)




[3 4 5]
[1 2 3 4 5 6 7]
[1 2]
[6 7]


---
## Parte 12 – Guardado y carga de arrays

### Ejercicio 25.
`np.save` y `np.load` son las funciones principales para guardar y leer arrays en disco en formato binario (`.npy`).
- Crea el array `arr = np.arange(10)`, guárdalo con `np.save("mi_array", arr)` y vuelve a cargarlo con `np.load("mi_array.npy")`. Verifica que el array recuperado es idéntico al original.
- Observa que si no incluyes la extensión `.npy` al guardar, NumPy la añade automáticamente.

In [ ]:
# Tu código aquí


### Ejercicio 26.
`np.savez` permite guardar varios arrays en un único archivo `.npz`.
- Crea `a = np.arange(10)` y `b = np.linspace(0, 1, 5)`. Guárdalos juntos con `np.savez("archivo", a=a, b=b)`.
- Cárgalos con `arch = np.load("archivo.npz")` y accede a cada array mediante `arch["a"]` y `arch["b"]`.
- Repite el proceso usando `np.savez_compressed`. ¿Qué diferencia hay entre ambas funciones según el libro?

In [ ]:
# Tu código aquí


---
## Desafío final

### Ejercicio 27.
Crea un array de 1000 valores generados aleatoriamente con una distribución normal. Luego:
1. Calcula la media y la desviación estándar usando métodos del array.
2. Cuenta cuántos valores son mayores que 0 (pista: usa una expresión booleana sobre el array).
3. Reemplaza todos los valores negativos por 0.

In [67]:
arr = np.random.randn(1000)

media = arr.mean()
print("media:", media)

arrmodificado = np.where(arr <= 0, 0, arr)
#print(arrmodificado)

sumatorio = (arr > 0).sum()
print("suma total:", sumatorio)

std = arr.std()
print("desviación estándar:", std)


media: -0.04846112456727731
suma total: 482
desviación estándar: 1.0582398703672966
